// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getcbar
double getcbar(double rhobar, const arma::mat& distmat);
RcppExport SEXP _spatialunitroot_getcbar(SEXP rhobarSEXP, SEXP distmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rhobar(rhobarSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    rcpp_result_gen = Rcpp::wrap(getcbar(rhobar, distmat));
    return rcpp_result_gen;
END_RCPP
}
// getpow_qf
double getpow_qf(const arma::mat& om0_in, const arma::mat& om1_in, const arma::mat& e);
RcppExport SEXP _spatialunitroot_getpow_qf(SEXP om0_inSEXP, SEXP om1_inSEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type om0_in(om0_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type om1_in(om1_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(getpow_qf(om0_in, om1_in, e));
    return rcpp_result_gen;
END_RCPP
}
// double_center
arma::mat double_center(const arma::mat& mat);
RcppExport SEXP _spatialunitroot_double_center(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(double_center(mat));
    return rcpp_result_gen;
END_RCPP
}
// sigma_lbm
arma::mat sigma_lbm(const arma::mat& distmat);
RcppExport SEXP _spatialunitroot_sigma_lbm(SEXP distmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma_lbm(distmat));
    return rcpp_result_gen;
END_RCPP
}
// sigma_lbm_dm
arma::mat sigma_lbm_dm(const arma::mat& distmat);
RcppExport SEXP _spatialunitroot_sigma_lbm_dm(SEXP distmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma_lbm_dm(distmat));
    return rcpp_result_gen;
END_RCPP
}
// sigma_dm
arma::mat sigma_dm(const arma::mat& distmat, double c);
RcppExport SEXP _spatialunitroot_sigma_dm(SEXP distmatSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma_dm(distmat, c));
    return rcpp_result_gen;
END_RCPP
}
// sigma_residual
arma::mat sigma_residual(const arma::mat& distmat, double c, const arma::mat& M);
RcppExport SEXP _spatialunitroot_sigma_residual(SEXP distmatSEXP, SEXP cSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma_residual(distmat, c, M));
    return rcpp_result_gen;
END_RCPP
}
// get_R
arma::mat get_R(const arma::mat& sigma, int q);
RcppExport SEXP _spatialunitroot_get_R(SEXP sigmaSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(get_R(sigma, q));
    return rcpp_result_gen;
END_RCPP
}
// lbm_gls_matrix
arma::mat lbm_gls_matrix(const arma::mat& distmat);
RcppExport SEXP _spatialunitroot_lbm_gls_matrix(SEXP distmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    rcpp_result_gen = Rcpp::wrap(lbm_gls_matrix(distmat));
    return rcpp_result_gen;
END_RCPP
}
// nn_matrix
arma::mat nn_matrix(const arma::mat& s, bool latlong);
RcppExport SEXP _spatialunitroot_nn_matrix(SEXP sSEXP, SEXP latlongSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< bool >::type latlong(latlongSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_matrix(s, latlong));
    return rcpp_result_gen;
END_RCPP
}
// iso_matrix
arma::mat iso_matrix(const arma::mat& s, double radius, bool latlong);
RcppExport SEXP _spatialunitroot_iso_matrix(SEXP sSEXP, SEXP radiusSEXP, SEXP latlongSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< bool >::type latlong(latlongSEXP);
    rcpp_result_gen = Rcpp::wrap(iso_matrix(s, radius, latlong));
    return rcpp_result_gen;
END_RCPP
}
// cluster_matrix
arma::mat cluster_matrix(const arma::vec& cluster);
RcppExport SEXP _spatialunitroot_cluster_matrix(SEXP clusterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type cluster(clusterSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_matrix(cluster));
    return rcpp_result_gen;
END_RCPP
}
// apply_transform
arma::vec apply_transform(const arma::vec& y, const arma::mat& H, bool is_lbmgls);
RcppExport SEXP _spatialunitroot_apply_transform(SEXP ySEXP, SEXP HSEXP, SEXP is_lbmglsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< bool >::type is_lbmgls(is_lbmglsSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_transform(y, H, is_lbmgls));
    return rcpp_result_gen;
END_RCPP
}
// lvech
arma::vec lvech(const arma::mat& S);
RcppExport SEXP _spatialunitroot_lvech(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(lvech(S));
    return rcpp_result_gen;
END_RCPP
}
// euclidean_distances
arma::mat euclidean_distances(const arma::mat& coords);
RcppExport SEXP _spatialunitroot_euclidean_distances(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_distances(coords));
    return rcpp_result_gen;
END_RCPP
}
// haversine_distances
arma::mat haversine_distances(const arma::mat& coords);
RcppExport SEXP _spatialunitroot_haversine_distances(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_distances(coords));
    return rcpp_result_gen;
END_RCPP
}
// normalize_distances
arma::mat normalize_distances(const arma::mat& distmat);
RcppExport SEXP _spatialunitroot_normalize_distances(SEXP distmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_distances(distmat));
    return rcpp_result_gen;
END_RCPP
}
// spatial_i1_test
Rcpp::List spatial_i1_test(const arma::vec& Y, const arma::mat& distmat, const arma::mat& emat, int q);
RcppExport SEXP _spatialunitroot_spatial_i1_test(SEXP YSEXP, SEXP distmatSEXP, SEXP ematSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_i1_test(Y, distmat, emat, q));
    return rcpp_result_gen;
END_RCPP
}
// spatial_i0_test
Rcpp::List spatial_i0_test(const arma::vec& Y, const arma::mat& distmat, const arma::mat& emat, int q);
RcppExport SEXP _spatialunitroot_spatial_i0_test(SEXP YSEXP, SEXP distmatSEXP, SEXP ematSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_i0_test(Y, distmat, emat, q));
    return rcpp_result_gen;
END_RCPP
}
// spatial_i1_test_residual
Rcpp::List spatial_i1_test_residual(const arma::vec& Y, const arma::mat& X_in, const arma::mat& distmat, const arma::mat& emat, int q);
RcppExport SEXP _spatialunitroot_spatial_i1_test_residual(SEXP YSEXP, SEXP X_inSEXP, SEXP distmatSEXP, SEXP ematSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_i1_test_residual(Y, X_in, distmat, emat, q));
    return rcpp_result_gen;
END_RCPP
}
// spatial_i0_test_residual
Rcpp::List spatial_i0_test_residual(const arma::vec& Y, const arma::mat& X_in, const arma::mat& distmat, const arma::mat& emat, int q);
RcppExport SEXP _spatialunitroot_spatial_i0_test_residual(SEXP YSEXP, SEXP X_inSEXP, SEXP distmatSEXP, SEXP ematSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_i0_test_residual(Y, X_in, distmat, emat, q));
    return rcpp_result_gen;
END_RCPP
}
// spatial_persistence
Rcpp::List spatial_persistence(const arma::vec& Z, const arma::mat& distmat, const arma::mat& emat, double level);
RcppExport SEXP _spatialunitroot_spatial_persistence(SEXP ZSEXP, SEXP distmatSEXP, SEXP ematSEXP, SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< double >::type level(levelSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_persistence(Z, distmat, emat, level));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spatialunitroot_getcbar", (DL_FUNC) &_spatialunitroot_getcbar, 2},
    {"_spatialunitroot_getpow_qf", (DL_FUNC) &_spatialunitroot_getpow_qf, 3},
    {"_spatialunitroot_double_center", (DL_FUNC) &_spatialunitroot_double_center, 1},
    {"_spatialunitroot_sigma_lbm", (DL_FUNC) &_spatialunitroot_sigma_lbm, 1},
    {"_spatialunitroot_sigma_lbm_dm", (DL_FUNC) &_spatialunitroot_sigma_lbm_dm, 1},
    {"_spatialunitroot_sigma_dm", (DL_FUNC) &_spatialunitroot_sigma_dm, 2},
    {"_spatialunitroot_sigma_residual", (DL_FUNC) &_spatialunitroot_sigma_residual, 3},
    {"_spatialunitroot_get_R", (DL_FUNC) &_spatialunitroot_get_R, 2},
    {"_spatialunitroot_lbm_gls_matrix", (DL_FUNC) &_spatialunitroot_lbm_gls_matrix, 1},
    {"_spatialunitroot_nn_matrix", (DL_FUNC) &_spatialunitroot_nn_matrix, 2},
    {"_spatialunitroot_iso_matrix", (DL_FUNC) &_spatialunitroot_iso_matrix, 3},
    {"_spatialunitroot_cluster_matrix", (DL_FUNC) &_spatialunitroot_cluster_matrix, 1},
    {"_spatialunitroot_apply_transform", (DL_FUNC) &_spatialunitroot_apply_transform, 3},
    {"_spatialunitroot_lvech", (DL_FUNC) &_spatialunitroot_lvech, 1},
    {"_spatialunitroot_euclidean_distances", (DL_FUNC) &_spatialunitroot_euclidean_distances, 1},
    {"_spatialunitroot_haversine_distances", (DL_FUNC) &_spatialunitroot_haversine_distances, 1},
    {"_spatialunitroot_normalize_distances", (DL_FUNC) &_spatialunitroot_normalize_distances, 1},
    {"_spatialunitroot_spatial_i1_test", (DL_FUNC) &_spatialunitroot_spatial_i1_test, 4},
    {"_spatialunitroot_spatial_i0_test", (DL_FUNC) &_spatialunitroot_spatial_i0_test, 4},
    {"_spatialunitroot_spatial_i1_test_residual", (DL_FUNC) &_spatialunitroot_spatial_i1_test_residual, 5},
    {"_spatialunitroot_spatial_i0_test_residual", (DL_FUNC) &_spatialunitroot_spatial_i0_test_residual, 5},
    {"_spatialunitroot_spatial_persistence", (DL_FUNC) &_spatialunitroot_spatial_persistence, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_spatialunitroot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
