# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find c such that mean(exp(-c * lower_tri(distmat))) equals rhobar
#'
#' Uses exponential bracketing followed by geometric bisection.
#' Matches the Stata getcbar() function exactly.
#' @param rhobar Target correlation
#' @param distmat n x n distance matrix
#' @return The constant cbar
getcbar <- function(rhobar, distmat) {
    .Call(`_spatialunitroot_getcbar`, rhobar, distmat)
}

#' Compute power of quadratic form test
#'
#' Compares quadratic forms under null (om0) vs alternative (om1) covariance.
#' Matches the Stata getpow_qf() function.
#' @param om0 Null hypothesis covariance matrix (q x q)
#' @param om1 Alternative hypothesis covariance matrix (q x q)
#' @param e q x nrep matrix of standard normal draws
#' @return Power (scalar between 0 and 1)
getpow_qf <- function(om0_in, om1_in, e) {
    .Call(`_spatialunitroot_getpow_qf`, om0_in, om1_in, e)
}

#' Double-center a matrix (subtract row means, then column means)
#'
#' Matches the Stata demeanmat() function.
#' @param mat n x n matrix
#' @return Double-centered matrix
double_center <- function(mat) {
    .Call(`_spatialunitroot_double_center`, mat)
}

#' Compute LBM covariance matrix from distance matrix
#'
#' sigma_lbm = 0.5 * (J * dist[,1]' + dist[1,] * J' - dist)
#' Uses the first location as the origin.
#' @param distmat n x n distance matrix
#' @return n x n LBM covariance matrix
sigma_lbm <- function(distmat) {
    .Call(`_spatialunitroot_sigma_lbm`, distmat)
}

#' Compute demeaned LBM covariance matrix
#'
#' sigma_lbm_dm = demeanmat(sigma_lbm(distmat))
#' @param distmat n x n distance matrix
#' @return Double-centered LBM covariance matrix
sigma_lbm_dm <- function(distmat) {
    .Call(`_spatialunitroot_sigma_lbm_dm`, distmat)
}

#' Compute demeaned spatial covariance with exponential decay
#'
#' sigma = exp(-c * distmat), then double-center.
#' @param distmat n x n distance matrix
#' @param c Decay parameter
#' @return Double-centered exponential covariance matrix
sigma_dm <- function(distmat, c) {
    .Call(`_spatialunitroot_sigma_dm`, distmat, c)
}

#' Compute residual-projected spatial covariance
#'
#' sigma = exp(-c * distmat), then sigma_dm = M * sigma * M'.
#' @param distmat n x n distance matrix
#' @param c Decay parameter
#' @param M n x n projection matrix (I - X(X'X)^{-1}X')
#' @return Residual-projected covariance matrix
sigma_residual <- function(distmat, c, M) {
    .Call(`_spatialunitroot_sigma_residual`, distmat, c, M)
}

#' Get top q eigenvectors of a symmetric matrix
#'
#' Computes eigendecomposition, sorts eigenvalues descending,
#' returns first q eigenvectors.
#' Matches the Stata get_R() function.
#' @param sigma n x n symmetric matrix
#' @param q Number of eigenvectors to extract
#' @return n x q matrix of top eigenvectors
get_R <- function(sigma, q) {
    .Call(`_spatialunitroot_get_R`, sigma, q)
}

#' Compute LBM-GLS transformation matrix
#'
#' From sigma_lbm_dm eigendecomposition, keep eigenvalues > 1e-10,
#' return V * diag(1/sqrt(eval)) * V'.
#' @param distmat n x n distance matrix
#' @return n x n LBM-GLS transformation matrix
lbm_gls_matrix <- function(distmat) {
    .Call(`_spatialunitroot_lbm_gls_matrix`, distmat)
}

#' Compute nearest-neighbor transformation matrix
#'
#' NN_mat = I - rowmins_mat, where each row has 1/k for the k nearest neighbors.
#' @param s n x d matrix of locations
#' @param latlong Whether coordinates are latitude/longitude
#' @return n x n NN transformation matrix
nn_matrix <- function(s, latlong) {
    .Call(`_spatialunitroot_nn_matrix`, s, latlong)
}

#' Compute isotropic transformation matrix
#'
#' iso_mat = I - dist_below_b / rowsum(dist_below_b)
#' where dist_below_b indicates distances <= radius
#' @param s n x d matrix of locations
#' @param radius Radius for differencing
#' @param latlong Whether coordinates are latitude/longitude
#' @return n x n isotropic transformation matrix
iso_matrix <- function(s, radius, latlong) {
    .Call(`_spatialunitroot_iso_matrix`, s, radius, latlong)
}

#' Compute cluster transformation matrix
#'
#' clust_mat = I - (clust_id == clust_id') / rowsum(clust_id == clust_id')
#' @param cluster n x 1 vector of integer cluster IDs
#' @return n x n cluster transformation matrix
cluster_matrix <- function(cluster) {
    .Call(`_spatialunitroot_cluster_matrix`, cluster)
}

#' Apply transformation matrix to a variable
#'
#' hy = H * y. For lbmgls, additionally mean-center the result.
#' @param y n x 1 vector
#' @param H n x n transformation matrix
#' @param is_lbmgls Whether to mean-center the result
#' @return n x 1 transformed vector
apply_transform <- function(y, H, is_lbmgls) {
    .Call(`_spatialunitroot_apply_transform`, y, H, is_lbmgls)
}

#' Half-vectorization: extract lower triangular elements (excluding diagonal)
#'
#' Matches the Stata lvech() function.
#' @param S n x n matrix
#' @return Column vector of lower-triangular elements
lvech <- function(S) {
    .Call(`_spatialunitroot_lvech`, S)
}

#' Compute Euclidean distance matrix
#'
#' @param coords n x d matrix of coordinates
#' @return n x n Euclidean distance matrix
euclidean_distances <- function(coords) {
    .Call(`_spatialunitroot_euclidean_distances`, coords)
}

#' Compute Haversine great-circle distance matrix
#'
#' Distances are divided by pi to match Stata convention (fraction of
#' semi-circle, so max distance = 1).
#'
#' @param coords n x 2 matrix with latitude in column 0, longitude in column 1
#' @return n x n Haversine distance matrix (scaled by 1/pi)
haversine_distances <- function(coords) {
    .Call(`_spatialunitroot_haversine_distances`, coords)
}

#' Normalize distance matrix so maximum distance is 1
#'
#' @param distmat n x n distance matrix
#' @return Normalized distance matrix
normalize_distances <- function(distmat) {
    .Call(`_spatialunitroot_normalize_distances`, distmat)
}

#' Spatial I(1) unit root test
#'
#' Tests H0: spatial unit root (I(1)) vs H1: not I(1).
#' @param Y n x 1 vector of observations
#' @param distmat n x n normalized distance matrix
#' @param emat q x nrep matrix of standard normal draws
#' @param q Number of low-frequency components
#' @return List with LR, pvalue, ha_parm, cv_vec
spatial_i1_test <- function(Y, distmat, emat, q) {
    .Call(`_spatialunitroot_spatial_i1_test`, Y, distmat, emat, q)
}

#' Spatial I(0) unit root test
#'
#' Tests H0: no spatial unit root (I(0)) vs H1: spatial unit root.
#' Uses a grid of rho values for the null hypothesis.
#' @param Y n x 1 vector of observations
#' @param distmat n x n normalized distance matrix
#' @param emat q x nrep matrix of standard normal draws
#' @param q Number of low-frequency components
#' @return List with LR, pvalue, cvalue, ha_parm, rho_grid, pvalue_mat, cvalue_mat
spatial_i0_test <- function(Y, distmat, emat, q) {
    .Call(`_spatialunitroot_spatial_i0_test`, Y, distmat, emat, q)
}

#' Spatial I(1) residual unit root test
#'
#' Tests residuals from regression Y on X for spatial unit root.
#' @param Y n x 1 response vector
#' @param X_in n x k design matrix (including intercept)
#' @param distmat n x n normalized distance matrix
#' @param emat q x nrep matrix of standard normal draws
#' @param q Number of low-frequency components
#' @return List with LR, pvalue, ha_parm, cv_vec
spatial_i1_test_residual <- function(Y, X_in, distmat, emat, q) {
    .Call(`_spatialunitroot_spatial_i1_test_residual`, Y, X_in, distmat, emat, q)
}

#' Spatial I(0) residual unit root test
#'
#' Tests residuals from regression Y on X for no spatial unit root (I(0)).
#' @param Y n x 1 response vector
#' @param X_in n x k design matrix (including intercept)
#' @param distmat n x n normalized distance matrix
#' @param emat q x nrep matrix of standard normal draws
#' @param q Number of low-frequency components
#' @return List with LR, pvalue, cvalue, ha_parm, rho_grid, pvalue_mat, cvalue_mat
spatial_i0_test_residual <- function(Y, X_in, distmat, emat, q) {
    .Call(`_spatialunitroot_spatial_i0_test_residual`, Y, X_in, distmat, emat, q)
}

#' Compute spatial half-life confidence interval
#'
#' Implements the Bayesian posterior-based confidence set for the
#' spatial half-life parameter. Matches Stata spatial_persistence().
#' @param Z n x 1 vector of observations
#' @param distmat n x n normalized distance matrix
#' @param emat q x nrep matrix of standard normal draws
#' @param level Confidence level (e.g., 0.95)
#' @return List with ci_lower, ci_upper
spatial_persistence <- function(Z, distmat, emat, level) {
    .Call(`_spatialunitroot_spatial_persistence`, Z, distmat, emat, level)
}

